swagger: "2.0"
info:
  title: "TOPCODER EMAIL SERIES - EMAIL SERVER"
  description: "TOPCODER EMAIL SERIES - EMAIL SERVER"
  version: "1.0.0"
host: "localhost:6100"
basePath : "/v5/email"
schemes:
- "https"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    description: JWT Authentication. Provide API Key in the form 'Bearer &lt;token&gt;'.

paths:
  /health:
    get:
      description:
        health check endpoint
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              health:
                type: string
definitions:
  Error:
    properties:
      error:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            message:
              type: string
            path:
              type: string
            type:
              type: string
            context:
              type: object
